# Generated by Django 4.0.3 on 2022-03-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('ActorID', models.CharField(max_length=255)),
                ('ActorName', models.CharField(max_length=255)),
                ('AnswerAvailable', models.CharField(max_length=255)),
                ('IsSaved', models.BooleanField(default=True)),
                ('IsVote', models.BooleanField(default=True)),
                ('Accepted', models.BooleanField(default=True)),
                ('Vote', models.IntegerField(default=0)),
                ('CreatedAtDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
