# Generated by Django 4.0.3 on 2022-03-05 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Accepted',
            new_name='accepted',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ActorID',
            new_name='actor_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ActorName',
            new_name='actor_name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='AnswerAvailable',
            new_name='answerAvailable',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='CreatedAtDate',
            new_name='createdAtDate',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='IsSaved',
            new_name='isSaved',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='IsVote',
            new_name='isVote',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Vote',
            new_name='vote',
        ),
    ]
