# Generated by Django 4.0.3 on 2022-03-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_rename_accepted_question_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='createdAtDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
